name = "email-explorer"
compatibility_date = "2026-02-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "email-explorer-db"
database_id = "f16fd67f-09f0-4854-9a2a-8d0bfe55b38a
"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "email-explorer"

[[durable_objects.bindings]]
name = "MAILBOX"
class_name = "MailboxDO"
script_name = "email-explorer"
